image: maven:3-jdk-8

cache:
  paths:
    - core/target/

variables:
  MAVEN_OPTS: -Dmaven.repo.local=/cache/maven.repository

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test
  artifacts:
    reports:
      junit:
        - core/target/surefire-reports/TEST-*.xml

deploy:
  stage: deploy
  script:
    - mvn deploy -DskipTests
