
name: Java CI with Maven

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        chmod +x mvnw
        ./mvnw -B package --file pom.xml --fail-at-end -DskipTests

    - name: Unit tests
      run: ./mvnw -B verify --file pom.xml --fail-at-end -Dmaven.test.redirectTestOutputToFile=true

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.2.0
      if: ${{ always() && !env.ACT }}
      with:
        check_name: Unit Test Results
        junit_files: '**/target/surefire-reports/TEST-*.xml'

    - name: Upload unit test results
      uses: actions/upload-artifact@v3
      if: ${{ failure() && !env.ACT }}
      with:
        name: unit-test-reports
        path: |
          '**/target/surefire-reports/TEST-*.xml'
          '**/target/surefire-reports/*-output.txt'
        retention-days: 5
